# Generated by Django 5.1 on 2024-10-08 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighbourhood', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('num_rooms', models.IntegerField()),
                ('num_banos', models.IntegerField()),
                ('size', models.FloatField()),
                ('age', models.IntegerField()),
                ('wifi', models.BooleanField(default=False)),
                ('air_conditioner', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('terrace', models.BooleanField(default=False)),
                ('garden', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('heater', models.BooleanField(default=False)),
                ('washing_machine', models.BooleanField(default=False)),
                ('dryer', models.BooleanField(default=False)),
                ('chimney', models.BooleanField(default=False)),
                ('jacuzzi', models.BooleanField(default=False)),
                ('sauna', models.BooleanField(default=False)),
                ('board_games', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
