# Generated by Django 5.1 on 2024-10-04 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('property_type', models.CharField(max_length=50)),
                ('num_rooms', models.IntegerField()),
                ('num_bathrooms', models.IntegerField()),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_administration', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('age', models.IntegerField()),
                ('garages', models.IntegerField()),
                ('stratum', models.IntegerField()),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nightly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_saved', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
