# Generated by Django 5.1 on 2024-10-04 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valorizacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='neighborhood',
            new_name='neighbourhood',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='num_bathrooms',
            new_name='num_banos',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='address',
        ),
        migrations.RemoveField(
            model_name='property',
            name='date_saved',
        ),
        migrations.RemoveField(
            model_name='property',
            name='nightly_price',
        ),
    ]
