# Generated by Django 5.1 on 2024-10-04 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valorizacion', '0004_rename_garages_property_garajes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='garajes',
            new_name='garages',
        ),
    ]
