# Generated by Django 5.1 on 2024-10-04 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valorizacion', '0005_rename_garajes_property_garages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='garages',
            new_name='garajes',
        ),
    ]
